version: '3'

services:
  squid:
    #image: jpvriel/squid
    image: sameersbn/squid:3.5.27
    ports:
      - "3128:3128"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - ./squid_passwd:/etc/squid/squid_passwd
    restart: always
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - 8090:80
  proxy:
    image: pottava/proxy
    ports:
      - 17780:80
    environment:
      - PROXY_URL=http://google.com/
      - BASIC_AUTH_USER=user1
      - BASIC_AUTH_PASS=pass1
      - ACCESS_LOG=true
    container_name: pottava-proxy
